config/routes.rb
Rails.application.routes.draw do
  resources :boards, only: [:new, :create, :index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'boards#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  attr_accessor :width, :height, :number_of_mines

  validates :email, presence: true
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[show update destroy]

  # GET /boards or /boards.json
  def index
    @boards = Board.all
    @boards = @boards.order('created_at desc').limit(10) if params[:view_all].blank?
  end

  # GET /boards/1 or /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # POST /boards or /boards.json
  def create
    board = Board.new(board_params)
    rows = board_params[:width].to_i
    cols = board_params[:height].to_i
    number_of_mines = board_params[:number_of_mines].to_i

    BoardService.new(rows, cols, number_of_mines, board).create

    redirect_to board_url(board)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:name, :email, :width, :height, :number_of_mines)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.erb
<div id="<%= dom_id board %>">
  <p>
    <strong>Name:</strong>
    <%= board.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= board.email %>
  </p>

  <p>
    <strong>Generated Board:</strong>
  </p>
  
  <div>
    <% JSON.parse(board&.mine).each_with_index do |sub_array, index| %>
      <% sub_array.each_with_index do |item, i| %>
        <% if item == 0 %>
          <i class="fa-sharp fa-solid fa-square fa-lg" style="color: #d7e0ef;"></i>
        <% else%>
          <i class="fa-solid fa-bomb fa-lg"></i>
        <% end%>
      <% end%>
      <br/>
    <% end%>
  </div>

</div>

app/views/boards/_form.html.erb
<%= bootstrap_form_for(@board) do |f| %>
  <%= f.email_field :email %>
  <%= f.text_field :name %>
  <%= f.text_field :width %>
  <%= f.text_field :height %>
  <%= f.text_field :number_of_mines %>
  <%= f.submit "Create" %>
<% end %>

app/views/boards/index.html.erb
<div class="p-5">

  <h1>Boards</h1>

  <div id="boards">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Created At</th>
        </tr>
      </thead>

      <tbody>
      <% @boards.each do |board| %>
        <tr>
          <td><%= link_to board.name, board %></td>
          <td><%= board.email%></td>
          <td><%= board.created_at%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to "New board", new_board_path, class: "btn btn-primary"%>
  <%= link_to "View all generated boards", boards_path(view_all: true), class: "btn btn-primary"%>
</div>

app/views/boards/new.html.erb
<div class="p-5">
  <h1>New board</h1>

  <%= render "form", board: @board %>

  <br>

  <div>
    <%= link_to "Back to boards", boards_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/boards/show.html.erb
<div class="p-5">
  <p style="color: green"><%= notice %></p>

  <%= render @board %>
    
    <div class="mt-5">
      <%= link_to "Back to boards", boards_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MinesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>